version: '3.8'
services:
  web:
    container_name: flask-container
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+mysqlconnector://root:app@db/blogdb
    volumes:
      - .:/code

  db:
    container_name: db-container
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: app
    ports:
      - "3306:3307"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  
