version: '3.8'
services:
  web:
    container_name: flask-container
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - db
    volumes:
      - .:/code

  db:
    container_name: db-container
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: blogdb
      MYSQL_ROOT_PASSWORD: app
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
  
